import { IVerifyEmailOTPResponse } from "../../interface/otpRequest";
import { IClientDashboardResponse } from "../../interface/clientDashboard";

const DEMO_DELAY_MS = 300;

const wait = (ms: number) =>
  new Promise((resolve) => {
    setTimeout(resolve, ms);
  });

const demoImpersonateUserResponse = {
  status: true,
  statusCode: 200,
  message: "Impersonated the user successfully!",
  data: {
    userID: "08de0598-4bee-48ca-8a7c-005b36583e79",
    userName: "NEXUS NUTRI SCIENCE LIMITED",
    showPanDetailPopUp: false,
    emailID: "QGbhj6TQHkSdcMwrOQjuXnJm9WgL5JmzhNFbOyF3+QA=",
    mobileNumber: "7UnlDe9E9Dd9xrAPlVCSAQ==",
    token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Ik51c0JFTWZlWkdNOVZsSjZJb21kYjU1UG5DQ3VwcHBwdmlmWk52QWFoSXkveVlIRzVKbGhXU1llWTM1bTZaU3kiLCJuYmYiOjE3NzYxNjA2OTMsImV4cCI6MTc3NjI0NzA5MywiaWF0IjoxNzc2MTYwNjkzfQ.Qph5BLfmqYB-heZ5IleZXexFlvvr-JeWX-AAYa0-eZQ",
    userType: 4,
    panTypeID: 2,
    roleID: 4,
    panNumber: "cgsUTjP4e1TKDstAGzjwUw==",
    gstNumber: "djtPZLt2l6mxlm5kPD32xw==",
    roleName: "Client",
    profilePicture:
      "https://i.postimg.cc/Njq5CnTY/credorbit-logo.jpg",
    contractEnforcementDate: "2025-10-09T00:00:00",
    isDefaultCpClient: false,
    isContractSigned: true,
    permissions: [
      { rightID: 1, parentID: 0, rightName: "Dashboard", create: null, delete: null, view: null, list: true, displayName: "Dashboard", displayOrder: 1 },
      { rightID: 2, parentID: 0, rightName: "Profile", create: true, delete: null, view: null, list: true, displayName: "Profile", displayOrder: 2 },
      { rightID: 3, parentID: 23, rightName: "RoleMaster", create: null, delete: null, view: null, list: null, displayName: "Role Master", displayOrder: 5 },
      { rightID: 4, parentID: 14, rightName: "ClientMaster", create: null, delete: null, view: null, list: null, displayName: "Client Master", displayOrder: 7 },
      { rightID: 5, parentID: 14, rightName: "ChannelPartner", create: null, delete: null, view: null, list: null, displayName: "Channel Partner", displayOrder: 8 },
      { rightID: 6, parentID: 14, rightName: "SourcingPartner", create: null, delete: null, view: null, list: null, displayName: "Sourcing Partner", displayOrder: 9 },
      { rightID: 7, parentID: 0, rightName: "Reports", create: null, delete: null, view: true, list: true, displayName: "Reports", displayOrder: 10 },
      { rightID: 8, parentID: 15, rightName: "ContractChannelPartner", create: null, delete: null, view: null, list: null, displayName: "Channel Partner Contract ", displayOrder: 14 },
      { rightID: 9, parentID: 15, rightName: "ContractSourcingPartner", create: null, delete: null, view: null, list: null, displayName: "Sourcing Partner Contract ", displayOrder: 15 },
      { rightID: 10, parentID: 15, rightName: "ContractClient", create: null, delete: null, view: null, list: true, displayName: "Client Contract ", displayOrder: 16 },
      { rightID: 11, parentID: 0, rightName: "Policy", create: null, delete: null, view: null, list: false, displayName: "Policy", displayOrder: 17 },
      { rightID: 12, parentID: 0, rightName: "Support", create: null, delete: null, view: null, list: true, displayName: "Support", displayOrder: 18 },
      { rightID: 13, parentID: 0, rightName: "PayOuts", create: null, delete: null, view: null, list: null, displayName: "Payouts", displayOrder: 20 },
      { rightID: 14, parentID: 0, rightName: "UserMaster", create: null, delete: null, view: null, list: null, displayName: "Master", displayOrder: 6 },
      { rightID: 15, parentID: 0, rightName: "Contracts", create: null, delete: null, view: null, list: true, displayName: "Contracts", displayOrder: 13 },
      { rightID: 16, parentID: 0, rightName: "TermsAndConditions", create: null, delete: null, view: null, list: null, displayName: "Terms & Conditions", displayOrder: 19 },
      { rightID: 17, parentID: 0, rightName: "Subscription", create: null, delete: null, view: null, list: true, displayName: "Subscription", displayOrder: 23 },
      { rightID: 18, parentID: 23, rightName: "ManageUsers", create: null, delete: null, view: null, list: null, displayName: "Manage Users", displayOrder: 4 },
      { rightID: 19, parentID: 7, rightName: "ChannelPartnerReport", create: null, delete: null, view: null, list: null, displayName: "Channel Partner Report", displayOrder: 11 },
      { rightID: 20, parentID: 7, rightName: "GeographicalReport", create: null, delete: null, view: null, list: null, displayName: "Geographical Report", displayOrder: 12 },
      { rightID: 21, parentID: 13, rightName: "ChannelPartnerPayout", create: null, delete: null, view: null, list: null, displayName: "My Payout", displayOrder: 21 },
      { rightID: 22, parentID: 13, rightName: "SourcingPartnerPayout", create: null, delete: null, view: null, list: null, displayName: "SP Payout", displayOrder: 22 },
      { rightID: 23, parentID: 0, rightName: "UserManagement", create: false, delete: null, view: false, list: false, displayName: "User Management", displayOrder: 3 },
    ],
  },
} as IVerifyEmailOTPResponse;

const demoClientDashboardResponse = {
  status: true,
  statusCode: 200,
  message: "List of all Loan Applications fetched successfully!",
  data: {
    creditScore: null,
    maxCreditScore: 900,
    creditScoreFetchedDate: "2026-04-01T12:49:17.964011",
    loanApplicationList: [
      {
        loanApplicationID: "08de9957-529b-4df9-83f6-e3ded4006a52",
        disbursementId: "00000000-0000-0000-0000-000000000000",
        loanApplicationCode: "COLA260423",
        bankName: null,
        loanType: "Home Loan",
        loanTypeID: 1,
        date: "2026-04-13",
        sanctionedDate: null,
        disbursedDate: null,
        loanAmount: 5000000.0,
        sanctionedLoanAmount: 5000000.0,
        disbursedLoanAmount: 100000.0,
        sanctionLetterUrl: null,
        customerName: "NEXUS NUTRI SCIENCE LIMITED",
        userID: "08de0598-4bee-48ca-8a7c-005b36583e79",
        progressPercent: 60,
        isCamReportGenerated: false,
        status: { label: "Disbursed", color: "#0BB680", statusID: 6 },
      },
      {
        loanApplicationID: "08de9601-76b5-4691-880a-1116e852fe41",
        disbursementId: "00000000-0000-0000-0000-000000000000",
        loanApplicationCode: "COLA260412",
        bankName: null,
        loanType: "Loan against property - Residential",
        loanTypeID: 7,
        date: "2026-04-09",
        sanctionedDate: null,
        disbursedDate: null,
        loanAmount: 5000000.0,
        sanctionedLoanAmount: 4000000.0,
        disbursedLoanAmount: 650000.0,
        sanctionLetterUrl: null,
        customerName: "NEXUS NUTRI SCIENCE LIMITED",
        userID: "08de0598-4bee-48ca-8a7c-005b36583e79",
        progressPercent: 60,
        isCamReportGenerated: false,
        status: { label: "Disbursed", color: "#0BB680", statusID: 6 },
      },
      {
        loanApplicationID: "08de955e-20ce-444e-888c-8ad06a3b1f1a",
        disbursementId: "00000000-0000-0000-0000-000000000000",
        loanApplicationCode: "COLA260408",
        bankName: null,
        loanType: "CC/OD - Secured",
        loanTypeID: 10,
        date: "2026-04-08",
        sanctionedDate: null,
        disbursedDate: null,
        loanAmount: 30000000.0,
        sanctionedLoanAmount: null,
        disbursedLoanAmount: null,
        sanctionLetterUrl: null,
        customerName: "NEXUS NUTRI SCIENCE LIMITED",
        userID: "08de0598-4bee-48ca-8a7c-005b36583e79",
        progressPercent: 60,
        isCamReportGenerated: true,
        status: { label: "Pending", color: "#FF632C", statusID: 1 },
      },
      {
        loanApplicationID: "08de955a-236c-4f99-8f84-c84f7ae8f09d",
        disbursementId: "00000000-0000-0000-0000-000000000000",
        loanApplicationCode: "COLA260406",
        bankName: null,
        loanType: "Loan against property - Residential",
        loanTypeID: 7,
        date: "2026-04-08",
        sanctionedDate: null,
        disbursedDate: null,
        loanAmount: 3000000.0,
        sanctionedLoanAmount: null,
        disbursedLoanAmount: null,
        sanctionLetterUrl: null,
        customerName: "NEXUS NUTRI SCIENCE LIMITED",
        userID: "08de0598-4bee-48ca-8a7c-005b36583e79",
        progressPercent: 60,
        isCamReportGenerated: false,
        status: { label: "Pending", color: "#FF632C", statusID: 1 },
      },
      {
        loanApplicationID: "08de9555-c0d0-4a45-8a7f-4fbf1be1fdee",
        disbursementId: "00000000-0000-0000-0000-000000000000",
        loanApplicationCode: "COLA260405",
        bankName: null,
        loanType: "CC/OD - Secured",
        loanTypeID: 10,
        date: "2026-04-08",
        sanctionedDate: null,
        disbursedDate: null,
        loanAmount: 3000000.0,
        sanctionedLoanAmount: null,
        disbursedLoanAmount: null,
        sanctionLetterUrl: null,
        customerName: "NEXUS NUTRI SCIENCE LIMITED",
        userID: "08de0598-4bee-48ca-8a7c-005b36583e79",
        progressPercent: 60,
        isCamReportGenerated: false,
        status: { label: "Pending", color: "#FF632C", statusID: 1 },
      },
    ],
    reports: [
      { name: "GST Report", filePath: "/assets/images/GST Report.pdf", reportType: 5 },
      { name: "ITR Report", filePath: "/assets/images/ITR Report.pdf", reportType: 4 },
      { name: "Banking Report", filePath: "/assets/images/Banking Report.pdf", reportType: 3 },
      { name: "Credit Analytics Report", filePath: "/assets/images/Credit Analytics Report.pdf", reportType: 1 },
    ],
    creditReportDate: "2026-04-02T15:08:11.671899",
    bankingReportDate: "2026-03-20T14:25:56.378287",
    itrReportDate: null,
    gstReportDate: "2026-02-26T05:21:11.871114",
    rocReportDate: null,
    cfoReportDate: null,
    gstNumber: "djtPZLt2l6mxlm5kPD32xw==",
    gstList: [
      { id: 220, userId: "08de0598-4bee-48ca-8a7c-005b36583e79", gstNo: "qM1+glEUF++WdxM3oyACgw==", dateOfGstRegistration: null, tradeName: null, gstAddress: null, cinOrLLP: null, user: null },
      { id: 221, userId: "08de0598-4bee-48ca-8a7c-005b36583e79", gstNo: "LrDZ99I/RC7UGJElYhBrLQ==", dateOfGstRegistration: null, tradeName: null, gstAddress: null, cinOrLLP: null, user: null },
      { id: 222, userId: "08de0598-4bee-48ca-8a7c-005b36583e79", gstNo: "djtPZLt2l6mxlm5kPD32xw==", dateOfGstRegistration: null, tradeName: null, gstAddress: null, cinOrLLP: null, user: null },
    ],
    totalLoanApplicationsCountByStatus: [
      { displayName: "Total Applications", displayOrder: 0, amount: 0, noOfApplications: 9, formattedAmount: null, statusID: 0 },
      { displayName: "Login Applications", displayOrder: 2, amount: 0, noOfApplications: 0, formattedAmount: null, statusID: 2 },
      { displayName: "Sanctioned Applications", displayOrder: 4, amount: 0, noOfApplications: 0, formattedAmount: null, statusID: 4 },
    ],
    userDetails: {
      contractEnforcementDate: "2025-10-09T00:00:00",
      emailID: "QGbhj6TQHkSdcMwrOQjuXnJm9WgL5JmzhNFbOyF3+QA=",
      isContractSigned: true,
      profilePicture: "https://i.postimg.cc/Njq5CnTY/credorbit-logo.jpg",
      showPanDetailPopUp: false,
      userName: "NEXUS NUTRI SCIENCE LIMITED",
    },
    partners: [
      { id: "08de8f1c-36df-44e4-86a5-73ebfe34f5ac", name: "DEV SANJAYKUMAR BHUPTANI", firstName: "DEV", middleName: "SANJAYKUMAR", lastName: "BHUPTANI", pan: "yMxMPliigDtX5/toz6v+xQ==", aadhaarNumber: "5MQcIhAiN8RAsJHaUSjBQg==", address: "PXoBDi6i9qorLkeviDtw4yyMRsAroVxzarUsszuNKZeLZBF7F+jsDQviu8Qm62y1L0QGDfY1gaaPs1qEN86w2xnBSSe1R9N6mH6Llt7eisqXkb0jmXPRWdjgaPqISm4HFsWIV/ov3eculpS2VZqQ+V+WMGL0hnVxbQV7g4a/0eWm3LMqbORAsr7qsNyB2DeY", state: "BkFZ9XSp8OfIQZ3E6jrlAA==", city: "0/uFJ6slmmGhvzYYiBk81g==", pinCode: "1cqyY1btLiZmjXErd2u2Dg==", mobile: "vO5BMExR9EM6qawgtekoVg==", dateOfBirth: "DVXrbb2iCMu2YkMP3s4PyQ==", gender: "M", creditScore: null },
      { id: "08de8f1c-a869-4822-8f52-cea2d9323470", name: "RAHUL NEGI", firstName: "RAHUL", middleName: "", lastName: "NEGI", pan: "NadGzHcmxrOyYL6Xa+aJwA==", aadhaarNumber: "0SlZDHNVt4inOMDmEHOJvA==", address: "v8jip8Xrjw/26byPJcdnvr3JMZyiowj/5lii0NLyjVj4dE9LoxkN2tiotaLsy9XwrSNs/3/YuOnbjhvd5No6UMpLsngbMF2eX2J0/JbiRG+YDB0GZ/u0oq85d5L8xPV1", state: "J9zJBmmB4zDeQF4jdERuzw==", city: "5qKDxGSYTt593e3DQecRJg==", pinCode: "ewwNmyl1ZTmqkH/PQYYADg==", mobile: "Ents0fXvQkeeV1YXpanKSg==", dateOfBirth: "PyDaSrVhr6LKSJZ8rtYmvQ==", gender: "M", creditScore: null },
      { id: "08de8f1c-b63f-48ef-834a-27d9ac63fc5a", name: "DARSHAK ATULKUMAR ACHARYA", firstName: "DARSHAK", middleName: "ATULKUMAR", lastName: "ACHARYA", pan: "P4OJWWP5SgQ3vzk/ukhRmA==", aadhaarNumber: "rXgHI8q/qWT1mehve3IPxQ==", address: "foUByoj8GlaabUfAwsJakcuGkvGgMY8qgvK6v32GwAewlvC/dQ1p/1xG8/M7ka4gPvMwshvVOKEHbESDWkrq8W6z4PFihaxwGeQ4Ow+BP1w=", state: "BkFZ9XSp8OfIQZ3E6jrlAA==", city: "sttq+2jLhUB2djxOgMuSDQ==", pinCode: "Bodt782hYNRCusKVoxm4Nw==", mobile: "5U8wsmljtwmIsUU9juI9Yw==", dateOfBirth: "D60kyAv6XHMebIyhLZ1KGQ==", gender: "M", creditScore: null },
      { id: "08de8f46-aa27-475a-8aed-955af25bcc6f", name: "RAM SINGH BHANDARI", firstName: "RAM", middleName: "SINGH", lastName: "BHANDARI", pan: "7ZIchhrh7zQU1xSjpR6RWg==", aadhaarNumber: null, address: "", state: "", city: "", pinCode: "", mobile: "5FQXGGwZ6yFnp5YwnZnVbQ==", dateOfBirth: "u9aFC7qdvNaY/wiGhmpQnQ==", gender: "M", creditScore: null },
      { id: "08de8f48-7e49-495e-8838-3a1c25b67e97", name: "ASHOK SAINI", firstName: "ASHOK", middleName: "", lastName: "SAINI", pan: "iJ2tPLSwpMKeMIDLJ6fxIA==", aadhaarNumber: "Lz15O4Tp2hBBAcWonFQurw==", address: "FVb4EbrFWDnDsOWaoZ4ZWz7cHSfKFRm51sq0YUO5FY83Jcrwhm9dElg8DCppTk9kmWsyKrlxbzmEx3zowy3gwA==", state: "z19VcZmQerqZ/vPnKMQBOw==", city: "BBEGMk+3YfsK5alod0llrw==", pinCode: "Ilo/NZhmvrWBk3mV/6dlFA==", mobile: "17sBZ+HpFipZI5Alud/5RQ==", dateOfBirth: "uLfimPS8aVqYphDDG4hZKA==", gender: "M", creditScore: null },
      { id: "08de8f49-7b22-4059-8f5c-a39b3b3d2ca5", name: "OMPRAKASH GULAPPA BISNAL", firstName: "OMPRAKASH GULAPPA", middleName: "", lastName: "BISNAL", pan: "IuqZ5In9yiKTjEe9TP24ZA==", aadhaarNumber: "U/Dkaz0AQTEzYdgXsHZAYA==", address: "Cvfif2k9o/ALEuu5beLLEfRERgb0nD0Daqkw0n3GNVk/vQIGdUr4RWAG5QGopjocpfoqeW3Lm1SI5FU0v6pXYOe3i1sw1eCw8EMRZt8hPUXOvDcAaUJdRTvqkpt5FY6I7RZotM6LUmmURjnb1Hocs0EjAzQBahGefeaYvrAj13g=", state: "wydZscZyTjPAS6WhmEjL+w==", city: "5Rg0RWPjmNPXaAYH3/rK3w==", pinCode: "yUDmzmHxqEWthsZNuGIaXg==", mobile: "vxD5Ahi6OmAybA7qQR5Uxg==", dateOfBirth: "UvRQRNOG2XWoBIUpTz/iLw==", gender: "M", creditScore: null },
      { id: "08de8fab-7dbd-4bb2-8c80-3d2a5767190d", name: "KARAN RAI", firstName: "KARAN", middleName: "", lastName: "RAI", pan: "nH+TAIKCrJ2XFm/gjXt2kw==", aadhaarNumber: "Kn0ctiYNs+aXuSCOTZ4o/w==", address: "2e7b6BwJDQw3hckI8K5/y9bZgin/FEyXwimf8zwcvWi0gLYYL3/jmTFuq1kuGuahEOmlzko9+H/38gNt602K5a98Z6uZMPwIttEkFOFPEjc=", state: "fXBXw7uyF+PFS3l35+3h3g==", city: "xhz1fj4GN4kAFrqfBmFYug==", pinCode: "r4kp+XEFUeXJNaba0jb0yA==", mobile: "9AoQbOtlXb6R8Nyys2hhDQ==", dateOfBirth: "I4oZyJe8wR4LqCS/8mam7w==", gender: "M", creditScore: null },
      { id: "08de8fab-b8e0-4d09-82a4-b166e0053fa0", name: "RAM SINGH BHANDARI", firstName: "RAM", middleName: "SINGH", lastName: "BHANDARI", pan: "7ZIchhrh7zQU1xSjpR6RWg==", aadhaarNumber: null, address: "", state: "", city: "", pinCode: "", mobile: "5FQXGGwZ6yFnp5YwnZnVbQ==", dateOfBirth: "u9aFC7qdvNaY/wiGhmpQnQ==", gender: "M", creditScore: null },
      { id: "08de90a0-d788-4ff6-82ce-25c363c59baf", name: "DEV SANJAYKUMAR BHUPTANI", firstName: "DEV", middleName: "SANJAYKUMAR", lastName: "BHUPTANI", pan: "yMxMPliigDtX5/toz6v+xQ==", aadhaarNumber: "5MQcIhAiN8RAsJHaUSjBQg==", address: "PXoBDi6i9qorLkeviDtw4yyMRsAroVxzarUsszuNKZeLZBF7F+jsDQviu8Qm62y1L0QGDfY1gaaPs1qEN86w2xnBSSe1R9N6mH6Llt7eisqXkb0jmXPRWdjgaPqISm4HFsWIV/ov3eculpS2VZqQ+V+WMGL0hnVxbQV7g4a/0eWm3LMqbORAsr7qsNyB2DeY", state: "BkFZ9XSp8OfIQZ3E6jrlAA==", city: "0/uFJ6slmmGhvzYYiBk81g==", pinCode: "1cqyY1btLiZmjXErd2u2Dg==", mobile: "vO5BMExR9EM6qawgtekoVg==", dateOfBirth: "DVXrbb2iCMu2YkMP3s4PyQ==", gender: "M", creditScore: null },
      { id: "08de90a0-dfd7-4f41-8d66-883df7bdb523", name: "DARSHAK ATULKUMAR ACHARYA", firstName: "DARSHAK", middleName: "ATULKUMAR", lastName: "ACHARYA", pan: "P4OJWWP5SgQ3vzk/ukhRmA==", aadhaarNumber: "rXgHI8q/qWT1mehve3IPxQ==", address: "foUByoj8GlaabUfAwsJakcuGkvGgMY8qgvK6v32GwAewlvC/dQ1p/1xG8/M7ka4gPvMwshvVOKEHbESDWkrq8W6z4PFihaxwGeQ4Ow+BP1w=", state: "BkFZ9XSp8OfIQZ3E6jrlAA==", city: "sttq+2jLhUB2djxOgMuSDQ==", pinCode: "Bodt782hYNRCusKVoxm4Nw==", mobile: "5U8wsmljtwmIsUU9juI9Yw==", dateOfBirth: "D60kyAv6XHMebIyhLZ1KGQ==", gender: "M", creditScore: null },
      { id: "08de9956-ff7d-4dbe-88ee-0167cfd2bca4", name: "KARAN RAI", firstName: "KARAN", middleName: "", lastName: "RAI", pan: "nH+TAIKCrJ2XFm/gjXt2kw==", aadhaarNumber: "Kn0ctiYNs+aXuSCOTZ4o/w==", address: "2e7b6BwJDQw3hckI8K5/y9bZgin/FEyXwimf8zwcvWi0gLYYL3/jmTFuq1kuGuahEOmlzko9+H/38gNt602K5a98Z6uZMPwIttEkFOFPEjc=", state: "fXBXw7uyF+PFS3l35+3h3g==", city: "xhz1fj4GN4kAFrqfBmFYug==", pinCode: "r4kp+XEFUeXJNaba0jb0yA==", mobile: "9AoQbOtlXb6R8Nyys2hhDQ==", dateOfBirth: "I4oZyJe8wR4LqCS/8mam7w==", gender: "M", creditScore: null },
      { id: "08de99e5-5265-4696-85d7-129fd8a235c0", name: "ASHOK SAINI", firstName: "ASHOK", middleName: "", lastName: "SAINI", pan: "iJ2tPLSwpMKeMIDLJ6fxIA==", aadhaarNumber: "Lz15O4Tp2hBBAcWonFQurw==", address: "FVb4EbrFWDnDsOWaoZ4ZWz7cHSfKFRm51sq0YUO5FY83Jcrwhm9dElg8DCppTk9kmWsyKrlxbzmEx3zowy3gwA==", state: "z19VcZmQerqZ/vPnKMQBOw==", city: "BBEGMk+3YfsK5alod0llrw==", pinCode: "Ilo/NZhmvrWBk3mV/6dlFA==", mobile: "17sBZ+HpFipZI5Alud/5RQ==", dateOfBirth: "uLfimPS8aVqYphDDG4hZKA==", gender: "M", creditScore: null },
    ],
  },
} as IClientDashboardResponse;

export const getDemoImpersonateUser =
  async (): Promise<IVerifyEmailOTPResponse> => {
    await wait(DEMO_DELAY_MS);
    return demoImpersonateUserResponse;
  };

export const getDemoClientDashboard =
  async (): Promise<IClientDashboardResponse> => {
    await wait(DEMO_DELAY_MS);
    return demoClientDashboardResponse;
  };
