export const RoutePathConstant = {
  public: {
    login: "/login",
    register: "/register",
    congratulations: "/congratulations",
    policy: "/privacy-policy",
    termsConditions: "/terms-and-condition",
  },
  private: {
    dashboard: "/admin-dashboard",
    profile: "/profile",
    roleMaster: "/role-master",
    reports: "/reports",
    reportDetails: "/reports/:id",
    policy: "/policy",
    support: "/support",
    loanDetail: "/loan-details",
    applyLoan: "/apply-loan",
    editLoan: "/edit-loan",
    loanMarketPlace: "/loan-market-place",
    checkEligibility: "/check-eligibility",
    termsConditions: "/terms-condition",
    userManagement: "/user-management",
    userManagementCreate: "/user-management/create",
    userManagementView: "/user-management/view/:id",
    userManagementEdit: "/user-management/edit/:id",
    userManagementRights: "/user-management/rights/:id",
    notification: "/notification",
    managedWhiteLabelling: "/white-labelling",
    loanApplicationManagement: "/loan-application-management",
    educationManageStudents: "/education-portal/manage-students",
    educationAddStudent: "/education-portal/manage-students/create",
    educationEditStudent: "/education-portal/manage-students/create/:id",
    educationManageCourse: "/education-portal/manage-course",
    educationCourseDetail: "/education-portal/manage-course/:id",
    institueDashboard: "/educational-institute-dashboard",
    nbfcDashboard: "/nbfc-dashboard",
    studentDashboard: "/student-dashboard",
    educationLoanApplications: "/education-portal/loan-applications",
    educationStudentLoanApplication: "/education-portal/student-loan-application",
    educationStudentConsentVerification: "/education-portal/student-loan-application/verification",
    educationStudentBankDetails: "/education-portal/student-loan-application/bank-details",
    educationNbfcStudentApplications: "/education-portal/nbfc-student-applications",
    educationManagedNbfcLoanApplications: "/education-portal/managed-nbfc-loan-applications",
    educationNbfcStudentApplicationDetail:
      "/education-portal/nbfc-student-applications/:id",
    roleMasterCreate: "/role-master/create",
    roleMasterView: "/role-master/view/:id",
    roleMasterEdit: "/role-master/edit/:id",
    nbfcOperations: "/nbfc-operations",
    educationManagement: "/education-management",
    educationManagedInstitute: "/education-portal/managed-education-institute",
    educationManagedNbfc: "/education-portal/managed-nbfc",
    educationInstituteDetail: "/education-portal/managed-education-institute/:id",
    educationManagedNbfcDetail: "/education-portal/managed-nbfc/:id",
    educationStudentDetail360View: "/education-portal/students-360-view",
    educationStudentDetail360ViewDetailed: "/education-portal/students-360-view/:id",
    educationStudentDetail: "/education-portal/manage-students/:id",
    loanMarketPlaceForEducationInstitute: "/education-portal/loan-marketplace",
    breBuilder: "/bre-builder/:id",
    breBuilderDetail: "/bre-builder-detail/:id",
    runTimeLogs: "/run-time-logs",
    runTimeLogsDetails: "/run-time-logs/:id",
  },
};
