import { APIResponseEntity } from "../../interface/apiResponse";
import {
  IContractListItemData,
  IContractListParams,
  IContractListResponse,
  IContractParams,
  IContractResponse,
  IUpdatedContractBody,
  IUpdatedContractStatusBody,
  IUserListForAdminContractListItemData,
  IUserListForAdminContractListResponse,
} from "../../interface/contract";
import { ILogoutResponse } from "../../interface/logout";
import {
  IUpdateSupportData,
  ISupportDataResponse,
} from "../../interface/supportData";
import { CLIENT_ROLE, ContractSigned } from "../constants/constant";
import { ContractType } from "../constants/enum";
import { encryptVAPTData } from "../functions/encryptDecrypt";

const wait = (ms: number) =>
  new Promise((resolve) => {
    setTimeout(resolve, ms);
  });

const DEMO_DELAY_MS = 250;

const contractContentType1 = `<p><span class="ql-size-large">These Terms &amp; Conditions (â€œTermsâ€) govern your use of Credorbitâ€™s platform and services as a Channel Partner.</span></p><p><span class="ql-size-large">By registering and using the Platform, you (â€œChannel Partnerâ€ / â€œyouâ€) agree to comply with these Terms. These Terms constitute a binding agreement between Credorbit Technologies Private Limited and you.</span></p><p><strong class="ql-size-large">&nbsp;</strong></p><p><strong class="ql-size-large">1. Definitions</strong></p><p><span class="ql-size-large">1.1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><strong class="ql-size-large">Platform</strong><span class="ql-size-large">- The website, dashboards, or applications owned and operated by Credorbit.</span></p><p><span class="ql-size-large">1.2.&nbsp;&nbsp;&nbsp;&nbsp;</span><strong class="ql-size-large">Channel Partner</strong><span class="ql-size-large">- A registered user authorized to process financial product applications and use Credorbitâ€™s services.</span></p><p><span class="ql-size-large">1.3.&nbsp;&nbsp;&nbsp;&nbsp;</span><strong class="ql-size-large">Customer</strong><span class="ql-size-large">- The end client whose data or documents are uploaded by the Channel Partner.</span></p><p><span class="ql-size-large">1.4.&nbsp;&nbsp;&nbsp;&nbsp;</span><strong class="ql-size-large">CAM Report/Analysis Report</strong><span class="ql-size-large">- A document or analysis generated by Credorbit based on financial statements and documents provided by the customer or channel partner.</span></p><p><span class="ql-size-large">1.5.&nbsp;&nbsp;&nbsp;&nbsp;</span><strong class="ql-size-large">Wallet &amp; Subscription</strong><span class="ql-size-large">- Prepaid credits or subscription plans for access to CAM reports and related services.</span></p><p><span class="ql-size-large">1.6.&nbsp;&nbsp;&nbsp;&nbsp;</span><strong class="ql-size-large">Services</strong><span class="ql-size-large">- Includes CAM reports, Analysis reports, loan eligibility check, loan application processing, and any other services offered by Credorbit.</span></p><p><span class="ql-size-large">1.7.&nbsp;&nbsp;&nbsp;&nbsp;</span><strong class="ql-size-large">Thirdâ€‘Party Service Providers</strong><span class="ql-size-large">- Vendors Credorbit may use (e.g., payment gateways).</span></p><p><span class="ql-size-large">1.8.&nbsp;&nbsp;&nbsp;&nbsp;</span><strong class="ql-size-large">Data</strong><span class="ql-size-large">- Customer or partner data uploaded to the Platform.</span></p><p><span class="ql-size-large">&nbsp;</span></p><p><strong class="ql-size-large">2. Scope of Services</strong></p><p><br></p><p><span class="ql-size-large">Credorbit provides Channel Partners with:</span></p><ul><li><span class="ql-size-large">Onboard customer with PAN, Mobile Number and E-mail id</span></li><li><span class="ql-size-large">Instant Loan Eligibility check</span></li><li><span class="ql-size-large">Ability to upload and process customer financial data.</span></li><li><span class="ql-size-large">Generation of Analysis Reports</span></li><li><span class="ql-size-large">Automated generation of CAM reports</span></li><li><span class="ql-size-large">Wallet &amp; Subscription options to manage and pay for services.</span></li><li><span class="ql-size-large">Other tools or services Credorbit may introduce</span></li></ul><p><span class="ql-size-large">ï»¿</span></p><p><span class="ql-size-large">Credorbit may add, modify, or discontinue services at its discretion</span></p><p><span class="ql-size-large">&nbsp;</span></p><p><strong class="ql-size-large">3. CAM Report, Analysis Report and Loan Eligibility- Disclaimer</strong></p><ul><li><span class="ql-size-large">CAM reports and approval percentages are </span><strong class="ql-size-large">informational tools only</strong><span class="ql-size-large">.</span></li><li><span class="ql-size-large">They are generated automatically based </span><strong class="ql-size-large">solely on the data submitted by the Channel Partner</strong><span class="ql-size-large">.</span></li><li><span class="ql-size-large">Credorbit does </span><strong class="ql-size-large">not independently verify</strong><span class="ql-size-large"> the accuracy or completeness of Customer data.</span></li><li><span class="ql-size-large">These do </span><strong class="ql-size-large">not guarantee, promise, or assure</strong><span class="ql-size-large"> that any lender will approve or sanction a loan or financial product.</span></li><li><span class="ql-size-large">Lending decisions are entirely at the discretion of independent lenders.</span></li><li><span class="ql-size-large">Channel Partners must ensure Customers understand these limitations.</span></li><li><span class="ql-size-large">Use of CAM reports and approval percentages is entirely </span><strong class="ql-size-large">at your own risk</strong><span class="ql-size-large">.</span></li></ul><p><span class="ql-size-large">&nbsp;</span></p><p><strong class="ql-size-large">4. Registration &amp; Account</strong></p><p><span class="ql-size-large">4.1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Channel Partner must register using accurate, complete, and current information.</span></p><p><span class="ql-size-large">4.2.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;You are responsible for keeping login credentials secure, if any.</span></p><p><span class="ql-size-large">4.3.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;You must promptly update any changes to your details and notify Credorbit of unauthorized use.</span></p><p><span class="ql-size-large">&nbsp;</span></p><p><strong class="ql-size-large">5. Use of Data &amp; Customer Consent</strong></p><p><span class="ql-size-large">5.1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;You must obtain </span><strong class="ql-size-large">clear, explicit consent</strong><span class="ql-size-large"> from each Customer before uploading data or documents.</span></p><p><span class="ql-size-large">5.2.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;You warrant that you have lawful rights to share this data.</span></p><p><span class="ql-size-large">5.3.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Credorbit may request evidence of Customer consent or supporting documents.</span></p><p><span class="ql-size-large">&nbsp;</span></p><p><strong class="ql-size-large">6. Wallet &amp; Subscription</strong></p><p><span class="ql-size-large">6.1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Wallet credits and subscriptions are used to pay for CAM reports, analysis reports, checking eligibility, and other services offered by credorbit.</span></p><p><span class="ql-size-large"> 6.2.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Wallet credits are currently:</span></p><ul><li><span class="ql-size-large">Nonâ€‘transferable</span></li><li><span class="ql-size-large">Nonâ€‘refundable</span></li><li><span class="ql-size-large">Do not expire (subject to Credorbitâ€™s right to revise this policy in the future, with or without notice).</span></li></ul><p><span class="ql-size-large">6.3.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Subscription plans and inclusions are described on the Platform/website and may change.</span></p><p><span class="ql-size-large">&nbsp;</span></p><p><strong class="ql-size-large">7. Legal Compliance</strong></p><p><span class="ql-size-large">Channel Partner must comply with all applicable laws and regulations, including:</span></p><ul><li><span class="ql-size-large">Information Technology Act &amp; Rules</span></li><li><span class="ql-size-large">Personal Data Protection laws</span></li><li><span class="ql-size-large">Any other local laws applicable to data privacy and financial services.</span></li></ul><p><span class="ql-size-large">&nbsp;</span></p><p><strong class="ql-size-large">8. Communications</strong></p><p><span class="ql-size-large">By registering, you consent to receive communications from Credorbit (email, SMS, WhatsApp, or calls) about services, updates, or promotions.</span></p><p><br></p><p><strong class="ql-size-large">9. Limitation of Liability</strong></p><p><span class="ql-size-large">9.1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The Platform and Services (including analysis reports, CAM reports, loan eligibility etc.) are provided </span><strong class="ql-size-large">â€œAS ISâ€ and â€œAS AVAILABLE.â€</strong></p><p><span class="ql-size-large">9.2.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Credorbit makes </span><strong class="ql-size-large">no warranties</strong><span class="ql-size-large"> about accuracy, completeness, or uninterrupted service.</span></p><p><span class="ql-size-large">9.3.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Credorbit shall </span><strong class="ql-size-large">not be liable</strong><span class="ql-size-large"> for:</span></p><ul><li><span class="ql-size-large">Decisions or transactions based on CAM reports or analysis reports or loan eligibility</span></li><li><span class="ql-size-large">Loan rejections by lenders</span></li><li><span class="ql-size-large">Technical issues, downtime, or data inaccuracies</span></li><li><span class="ql-size-large">Indirect or consequential losses</span></li></ul><p><span class="ql-size-large">&nbsp;</span></p><p><strong class="ql-size-large">10. Indemnity</strong></p><p><span class="ql-size-large">You agree to indemnify Credorbit, its directors, employees, and affiliates against losses or claims arising from:</span></p><ul><li><span class="ql-size-large">Your misuse of the Platform</span></li><li><span class="ql-size-large">Uploading inaccurate or unauthorized data</span></li><li><span class="ql-size-large">Breach of these Terms or applicable laws</span></li></ul><p><span class="ql-size-large">&nbsp;</span></p><p><strong class="ql-size-large">11. Term &amp; Termination</strong></p><p><span class="ql-size-large">11.1.&nbsp;&nbsp;&nbsp;&nbsp;These Terms apply from the date you register and remain until terminated.</span></p><p><span class="ql-size-large">11.2.&nbsp;&nbsp;&nbsp;&nbsp;Credorbit may suspend or terminate your access if you breach these Terms.</span></p><p><span class="ql-size-large">11.3.&nbsp;&nbsp;&nbsp;&nbsp;Either party may terminate by written notice; all outstanding fees remain payable.</span></p><p><span class="ql-size-large">&nbsp;</span></p><p><strong class="ql-size-large">12. Governing Law &amp; Jurisdiction</strong></p><p><span class="ql-size-large">These Terms are governed by the laws of India. Courts at </span><strong class="ql-size-large">Ahmedabad</strong><span class="ql-size-large"> shall have exclusive jurisdiction.</span></p><p><strong class="ql-size-large">&nbsp;</strong></p><p><strong class="ql-size-large">13. Changes to Terms</strong></p><p><span class="ql-size-large">Credorbit may update these Terms at any time. Updated Terms will be posted on the Platform, and continued use means you accept them.</span></p><p><strong class="ql-size-large">&nbsp;</strong></p><p><strong class="ql-size-large">14. Contact</strong></p><p><span class="ql-size-large">For questions or support:</span></p><ul><li><strong class="ql-size-large">Email:</strong><span class="ql-size-large"> support@credorbit.com</span></li><li><strong class="ql-size-large">Tollâ€‘Free Number:</strong><span class="ql-size-large"> +91 98249 09300</span></li><li><strong class="ql-size-large">Address:</strong><span class="ql-size-large"> A/5, Fifth Floor, Safal Profitaire, Corporate Road, Prahladnagar, Ahmedabad-380015</span></li></ul>`;

const contractContentType2 = `<h2>Sourcing Partner Contract</h2><p><br></p><p><strong class="ql-size-large">Test Test</strong></p><p><strong class="ql-size-large">Test Test</strong></p>`;

const privacyPolicyContent = `<p>This Privacy Policy (â€œPolicyâ€) explains how Credorbit Technologies Private Limited (â€œCredOrbitâ€, â€œweâ€, â€œusâ€, or â€œourâ€) collects, uses, stores, shares, and protects your information when you visit our website [https://www.credorbit.com] (â€œWebsiteâ€) or use any of our services, including products, platforms, tools, features, or solutions offered through the Website (collectively referred to as â€œServicesâ€).</p><p><br></p><p>By accessing or using our Services, you acknowledge and accept the practices and policies described in this Policy and agree to our collection, use, and disclosure of your information as described herein.</p><p><br></p><p>1. Information We Collect</p><p><br></p><p>We collect the following categories of personal information (â€œPersonal Informationâ€) either directly from you, from public sources, or from third-party partners:</p><p><br></p><p>A. Information You Provide</p><p><br></p><p>Name</p><p>Mobile number</p><p>Email address</p><p>PAN, Aadhaar, or KYC documents</p><p>Address and contact details</p><p>Employment and income information</p><p>Bank account or payment details</p><p>Loan application or credit request details</p><p>Any other information voluntarily provided during account creation, onboarding, or availing services</p><p><br></p><p>B. Information Automatically Collected</p><p><br></p><p>IP address</p><p>Device information (browser, OS, device type)</p><p>Date and time of access</p><p>Location data (subject to permissions)</p><p>Usage behavior on the Website (clicks, pages visited, time spent, etc.)</p><p>Cookies and similar technologies (see Section 6)</p><p><br></p><p>2. How We Use Your Information</p><p><br></p><p>We use your information for the following purposes:</p><p><br></p><p>To verify your identity and conduct KYC</p><p><p>To process your loan or credit applications</p><p>To assess eligibility and creditworthiness</p><p>To enable onboarding with our partner institutions</p><p>To communicate with you (e.g., updates, offers, transaction alerts)</p><p>To provide, maintain, and improve our Website and Services</p><p>To personalize your experience on the Website</p><p>To comply with applicable legal obligations</p><p>To prevent fraud, enforce terms, and ensure platform security</p><p>For analytics, research, and product development</p><p><br></p><p>3. Disclosure of Your Information</p><p><br></p><p>We may share your Personal Information with lending partners, vendors, regulators, affiliates, and prospective buyers where needed to deliver services or comply with law.</p><p><br></p><p>4. Your Rights</p><p><br></p><p>You may request access, correction, deletion, consent withdrawal, and grievance redressal subject to applicable law.</p><p><br></p><p>5. Data Retention</p><p><br></p><p>We retain your information for as long as necessary to fulfill the purposes stated in this Policy, or as required by applicable law, regulatory requirements, or contractual obligations.</p><p><br></p><p>6. Cookies and Tracking Technologies</p><p><br></p><p>We use cookies and similar tracking technologies to enhance your experience, analyze usage, and deliver relevant content.</p><p><br></p><p>7. Data Security</p><p><br></p><p>We implement appropriate technical and organizational measures including SSL, access controls, and regular assessments.</p><p><br></p><p>8. Childrenâ€™s Privacy</p><p><br></p><p>Our Website is not intended for individuals under the age of 18.</p><p><br></p><p>9. Grievance Redressal</p><p><br></p><p>Grievance Officer</p><p>Name: Dhrumit Parikh</p><p>Email: dhrumit@msaca.co.in</p><p>Phone: +91 95375 45851</p><p>Address: A/5, Fifth Floor, Safal Profitaire, Corporate Road, Prahladnagar, Ahmedabad-380015</p><p>Working Hours: Monday â€“ Friday (10:00 AM â€“ 6:00 PM)</p><p>You can expect a response within 7 working days.</p><p><br></p><p>10. Legal Basis and Jurisdiction</p><p><br></p><p>This Policy is governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of courts in Ahmedabad, Gujarat, unless otherwise agreed.</p><p><br></p><p>11. Changes to This Policy</p><p><br></p><p>We may update this Policy from time to time.</p><p><br></p><p>12. Consent</p><p><br></p><p>By accessing or using the Website, you consent to the collection, use, processing, storage, and disclosure of your information in accordance with this Privacy Policy.</p><h1 class="ql-indent-1">Test Test</h1>`;

const termsContent = `<h2>Terms &amp; Conditions</h2><p><br></p><p>These demo terms govern use of the Credorbit demo portal and are displayed from a local static response instead of a live CMS API.</p><p><br></p><p>Using the portal means you accept these terms for demonstration, review, and training purposes only.</p>`;

type DemoContractRecord = {
  pageName: string;
  contractTypeID?: number;
  isAgreed: boolean | null;
  content: string;
  aadhaarNumber: string | null;
  updatedDate: string;
  contractVersion: number | null;
  contractEnforcementDate: string | null;
  contractUserMappingID: string | null;
};

const demoContracts: DemoContractRecord[] = [
  {
    pageName: ContractType.CONTRACT,
    contractTypeID: ContractSigned.ADMIN_TO_CP,
    isAgreed: true,
    content: contractContentType1,
    aadhaarNumber: null,
    updatedDate: "2025-10-09T17:17:43.109751",
    contractVersion: 62,
    contractEnforcementDate: "2025-10-09T00:00:00",
    contractUserMappingID: "08de0729-a841-458b-89c0-11456d713923",
  },
  {
    pageName: ContractType.CONTRACT,
    contractTypeID: ContractSigned.CP_TO_SP,
    isAgreed: null,
    content: contractContentType2,
    aadhaarNumber: null,
    updatedDate: "2025-09-23T12:50:25.107653",
    contractVersion: 23,
    contractEnforcementDate: "2025-09-24T00:00:00",
    contractUserMappingID: null,
  },
  {
    pageName: ContractType.CONTRACT,
    contractTypeID: ContractSigned.CLIENT,
    isAgreed: false,
    content: `<h2>Client Contract</h2><p><br></p><p>This is a demo client agreement shown from local mock data for the portal walkthrough.</p>`,
    aadhaarNumber: null,
    updatedDate: "2025-09-25T10:10:00",
    contractVersion: 11,
    contractEnforcementDate: "2025-09-26T00:00:00",
    contractUserMappingID: null,
  },
  {
    pageName: ContractType.PRIVACY_POLICY,
    isAgreed: false,
    content: privacyPolicyContent,
    aadhaarNumber: null,
    updatedDate: "2025-09-24T16:52:04.532336",
    contractVersion: null,
    contractEnforcementDate: null,
    contractUserMappingID: null,
  },
  {
    pageName: ContractType.TERMS_AND_CONDITIONS,
    isAgreed: false,
    content: termsContent,
    aadhaarNumber: null,
    updatedDate: "2025-09-24T16:52:04.532336",
    contractVersion: null,
    contractEnforcementDate: null,
    contractUserMappingID: null,
  },
];

const demoContractLists: Record<
  number,
  IContractListItemData[]
> = {
  [CLIENT_ROLE.CHANNEL_PARTNER]: [
    {
      id:
        "demo-contract-id-001" as unknown as number,

      name:
        "MNO USER",

      userCode:
        "DEMO-SP-001",

      mobileNumber:
        encryptVAPTData("9000000010"),

      contractSigned: null,

      isActive: true,
    },

    {
      id:
        "demo-contract-id-002" as unknown as number,

      name:
        "ABC SOURCE SP",

      userCode:
        "DEMO-SP-002",

      mobileNumber:
        encryptVAPTData("9000000011"),

      contractSigned:
        "2025-09-26T13:10:05",

      isActive: true,
    },

    {
      id:
        "demo-contract-id-003" as unknown as number,

      name:
        "XYZ BUSINESS SOLUTIONS LLP",

      userCode:
        "DEMO-SP-003",

      mobileNumber:
        encryptVAPTData("9000000012"),

      contractSigned: null,

      isActive: false,
    },

    {
      id:
        "demo-contract-id-004" as unknown as number,

      name:
        "OPQ USER",

      userCode:
        "DEMO-SP-004",

      mobileNumber:
        encryptVAPTData("9000000013"),

      contractSigned: null,

      isActive: false,
    },
  ],

  [CLIENT_ROLE.SOURCING_PARTNER]: [
    {
      id:
        "demo-contract-id-001" as unknown as number,

      name:
        "MNO USER",

      userCode:
        "DEMO-SP-001",

      mobileNumber:
        "9000000001",

      contractSigned: null,

      isActive: true,
    },

    {
      id:
        "demo-contract-id-002" as unknown as number,

      name:
        "ABC SOURCE SP",

      userCode:
        "DEMO-SP-002",

      mobileNumber:
        "9000000002",

      contractSigned:
        "2025-09-26T13:10:05",

      isActive: true,
    },

    {
      id:
        "demo-contract-id-003" as unknown as number,

      name:
        "XYZ BUSINESS SOLUTIONS LLP",

      userCode:
        "DEMO-SP-003",

      mobileNumber:
        "9000000003",

      contractSigned: null,

      isActive: false,
    },

    {
      id:
        "demo-contract-id-004" as unknown as number,

      name:
        "ABC INDUSTRIES PRIVATE LIMITED",

      userCode:
        "DEMO-SP-004",

      mobileNumber:
        "9000000004",

      contractSigned: null,

      isActive: false,
    },

    {
      id:
        "demo-contract-id-005" as unknown as number,

      name:
        "DEF INDUSTRIES PRIVATE LIMITED",

      userCode:
        "DEMO-SP-005",

      mobileNumber:
        "9000000005",

      contractSigned: null,

      isActive: false,
    },

    {
      id:
        "demo-contract-id-006" as unknown as number,

      name:
        "RST USER",

      userCode:
        "DEMO-SP-006",

      mobileNumber:
        "9000000006",

      contractSigned: null,

      isActive: false,
    },

    {
      id:
        "demo-contract-id-007" as unknown as number,

      name:
        "UVW USER",

      userCode:
        "DEMO-SP-007",

      mobileNumber:
        "9000000007",

      contractSigned: null,

      isActive: false,
    },

    {
      id:
        "demo-contract-id-008" as unknown as number,

      name:
        "JKL USER",

      userCode:
        "DEMO-SP-008",

      mobileNumber:
        "9000000008",

      contractSigned: null,

      isActive: false,
    },

    {
      id:
        "demo-contract-id-009" as unknown as number,

      name:
        "PQR USER",

      userCode:
        "DEMO-SP-009",

      mobileNumber:
        "9000000009",

      contractSigned: null,

      isActive: false,
    },

    {
      id:
        "demo-contract-id-010" as unknown as number,

      name:
        "GLOBAL TECH ENTERPRISES",

      userCode:
        "DEMO-SP-010",

      mobileNumber:
        "9000000010",

      contractSigned: null,

      isActive: false,
    },
  ],
};

const demoUserContracts: IUserListForAdminContractListItemData[] = [
  {
    id: "demo-client-1",

    name:
      "ABC INDUSTRIES PRIVATE LIMITED",

    userCode:
      "DEMO-USER-001",

    mobileNumber:
      encryptVAPTData("9000000001"),

    contractSigned:
      "2025-09-28T10:30:00",

    channelPartnerName:
      "MNO USER",

    sourcingPartnerName:
      "ABC SOURCE SP",

    isActive: true,
  },

  {
    id: "demo-client-2",

    name:
      "XYZ BUSINESS SOLUTIONS LLP",

    userCode:
      "DEMO-USER-002",

    mobileNumber:
      encryptVAPTData("9000000002"),

    contractSigned: null,

    channelPartnerName:
      "DEF INDUSTRIES PRIVATE LIMITED",

    sourcingPartnerName:
      null,

    isActive: true,
  },

  {
    id: "demo-client-3",

    name:
      "GLOBAL TECH ENTERPRISES",

    userCode:
      "DEMO-USER-003",

    mobileNumber:
      encryptVAPTData("9000000003"),

    contractSigned: null,

    channelPartnerName:
      "OPQ USER",

    sourcingPartnerName:
      null,

    isActive: false,
  },
];

let demoSupportData = [
  {
    id: 1,
    name: "Name",
    value: "Meghal Shah",
    updatedDate: "2025-05-09T10:51:29.315997",
  },
  {
    id: 2,
    name: "PhoneNumber",
    value: "9824909300",
    updatedDate: "2025-05-09T10:51:29.316216",
  },
  {
    id: 3,
    name: "WhatsappNumber",
    value: "9824909300",
    updatedDate: "2025-05-09T10:51:29.31625",
  },
  {
    id: 4,
    name: "EmailID",
    value: "test@mail.example.co.in",
    updatedDate: "2025-05-09T10:51:29.316279",
  },
];

const getContractRecord = (params: IContractParams) =>
  demoContracts.find(
    (item) =>
      item.pageName === params.pageName &&
      item.contractTypeID === params.contractTypeID
  ) ??
  demoContracts.find(
    (item) =>
      item.pageName === params.pageName && item.contractTypeID === undefined
  );

const paginate = <T>(items: T[], page = 1, pageSize = 10) => {
  const start = (page - 1) * pageSize;
  return items.slice(start, start + pageSize);
};

export const getDemoContent = async (
  params: IContractParams
): Promise<IContractResponse> => {
  await wait(DEMO_DELAY_MS);

  const contract = getContractRecord(params);

  if (!contract) {
    return {
      status: false,
      statusCode: 404,
      message: "Content not found.",
      data: {
        isAgreed: false,
        content: "",
        updatedDate: "",
      },
    };
  }

  return {
    status: true,
    statusCode: 200,
    message: "Content fetched successfully!",
    data: contract,
  } as unknown as IContractResponse;
};

export const updateDemoContent = async (
  body: IUpdatedContractBody
): Promise<ILogoutResponse> => {
  await wait(DEMO_DELAY_MS);

  const contract = getContractRecord({
    pageName: body.pageName,
    contractTypeID: body.contractID,
  });

  const now = new Date().toISOString();

  if (contract) {
    contract.content = body.description;
    contract.updatedDate = now;
    contract.contractEnforcementDate =
      body.contractEnforcementDate ?? contract.contractEnforcementDate;
    contract.contractVersion =
      contract.contractVersion !== null ? contract.contractVersion + 1 : null;
  } else {
    demoContracts.push({
      pageName: body.pageName,
      contractTypeID: body.contractID,
      isAgreed: false,
      content: body.description,
      aadhaarNumber: null,
      updatedDate: now,
      contractVersion: 1,
      contractEnforcementDate: body.contractEnforcementDate ?? null,
      contractUserMappingID: null,
    });
  }

  return {
    status: true,
    statusCode: 200,
    data: null,
    message: "Content updated successfully!",
  };
};

export const getDemoContractList = async (
  params: IContractListParams
): Promise<IContractListResponse> => {
  await wait(DEMO_DELAY_MS);

  const searchText = (params.user ?? params.search ?? "").trim().toLowerCase();
  const sourceList = demoContractLists[params.userType] ?? [];
  const filteredList = searchText
    ? sourceList.filter(
      (item) =>
        item.name.toLowerCase().includes(searchText) ||
        item.userCode.toLowerCase().includes(searchText)
    )
    : sourceList;

  return {
    status: true,
    statusCode: 200,
    message: "Content fetched successfully!",
    data: {
      totalCount: filteredList.length,
      contractList: paginate(filteredList, params.page, params.pageSize),
    },
  };
};

export const getDemoUserListForAdminContractList = async (
  params: IContractListParams
): Promise<IUserListForAdminContractListResponse> => {
  await wait(DEMO_DELAY_MS);

  const searchText = (params.search ?? params.user ?? "").trim().toLowerCase();
  const filteredList = searchText
    ? demoUserContracts.filter(
      (item) =>
        item.name.toLowerCase().includes(searchText) ||
        item.userCode.toLowerCase().includes(searchText) ||
        item.channelPartnerName.toLowerCase().includes(searchText)
    )
    : demoUserContracts;

  return {
    status: true,
    statusCode: 200,
    message: "Content fetched successfully!",
    data: {
      totalCount: filteredList.length,
      userList: paginate(filteredList, params.page, params.pageSize),
    },
  };
};

export const updateDemoContractStatus = async (
  body: IUpdatedContractStatusBody
): Promise<APIResponseEntity> => {
  await wait(DEMO_DELAY_MS);

  if (body.status) {
    demoContracts.forEach((item) => {
      if (item.pageName === ContractType.CONTRACT) {
        item.isAgreed = true;
      }
    });
  }

  return {
    status: true,
    statusCode: 200,
    message: "Contract status updated successfully!",
  };
};

export const getDemoSupportData = async (): Promise<ISupportDataResponse> => {
  await wait(DEMO_DELAY_MS);

  return {
    status: true,
    statusCode: 200,
    message: "Support data fetched successfully!",
    data: demoSupportData,
  };
};

export const updateDemoSupportData = async (
  body: IUpdateSupportData
): Promise<APIResponseEntity> => {
  await wait(DEMO_DELAY_MS);

  const now = new Date().toISOString();

  demoSupportData = [
    {
      id: 1,
      name: "Name",
      value: body.name,
      updatedDate: now,
    },
    {
      id: 2,
      name: "PhoneNumber",
      value: body.phoneNumber,
      updatedDate: now,
    },
    {
      id: 3,
      name: "WhatsappNumber",
      value: body.whatsappNumber,
      updatedDate: now,
    },
    {
      id: 4,
      name: "EmailID",
      value: body.email,
      updatedDate: now,
    },
  ];

  return {
    status: true,
    statusCode: 200,
    message: "Support data updated successfully!",
  };
};